import safety from '../../assets/audios/safety_plan.mp3';
import storyLong from '../../assets/audios/your_story_long.mp3';
import storyShort from '../../assets/audios/your_story.mp3';

export default [
  {
    uuid: 'faci_1',
    id: 1,
    name: 'គ្លីនិកសុខភាពឯកទេសកម្ពុជា',
    tels: '012345678',
    address: null,
    emails: '["clinic1@gmail.com"]',
    websites: '[]',
    facebook_pages: '[]',
    telegram_username: null,
    description: 'ឯកទេសផ្នែកជំងឺផ្លូវចិត្ត បញ្ហាផ្លូវភេទ និងសខុភាពបន្តរពូជប្រចាំអាសុី',
    latitude: null,
    longitude: null,
    facility_batch_id: 1,
    image_url: '',
    audio_url: '',
    audio: safety,
    image: require('../../assets/images/intro_1.jpg'),
  },
  {
    uuid: 'faci_2',
    id: 2,
    name: 'គ្លីនិកសុខភាពផ្លូវភេទ',
    tels: '012876543',
    address: null,
    emails: '["clinic2+1@gmail.com", "clinic2+2@gmail.com"]',
    websites: '[]',
    facebook_pages: '[]',
    telegram_username: null,
    description: 'ឯកទេសផ្នែកជំងឺផ្លូវចិត្ត បញ្ហាផ្លូវភេទ និងសខុភាពបន្តរពូជប្រចាំអាសុី',
    latitude: null,
    longitude: null,
    facility_batch_id: 1,
    image_url: '',
    audio_url: '',
    audio: storyLong,
    image: require('../../assets/images/intro_2.jpg'),
  },
  {
    uuid: 'faci_3',
    id: 3,
    name: 'គ្លីនិកសុខភាពឯកទេសសម្ភព និងកុមារ',
    tels: '098765432',
    address: null,
    emails: '["clinic3@gmail.com"]',
    websites: '[]',
    facebook_pages: '[]',
    telegram_username: null,
    description: 'ឯកទេសផ្នែកជំងឺផ្លូវចិត្ត បញ្ហាផ្លូវភេទ និងសខុភាពបន្តរពូជប្រចាំអាសុី',
    latitude: null,
    longitude: null,
    facility_batch_id: 1,
    image_url: '',
    audio_url: '',
    audio: storyShort,
    image: require('../../assets/images/intro_3.jpg'),
  },
  {
    uuid: 'faci_4',
    id: 4,
    name: 'គ្លីនិកសុខភាពឯកទេសកម្ពុជា',
    tels: '011123123',
    address: null,
    emails: '["clinic4@gmail.com"]',
    websites: '[]',
    facebook_pages: '[]',
    telegram_username: null,
    description: 'ឯកទេសផ្នែកជំងឺផ្លូវចិត្ត បញ្ហាផ្លូវភេទ និងសខុភាពបន្តរពូជប្រចាំអាសុី',
    latitude: null,
    longitude: null,
    facility_batch_id: 1,
    image_url: '',
    audio_url: '',
    audio: '',
    image: require('../../assets/images/intro_1.jpg'),
  },
  {
    uuid: 'faci_5',
    id: 5,
    name: 'គ្លីនិកសុខភាពឯកទេសសម្ភព និងកុមារ',
    tels: '070987654',
    address: null,
    emails: '["clinic5@gmail.com"]',
    websites: '[]',
    facebook_pages: '[]',
    telegram_username: null,
    description: 'ឯកទេសផ្នែកជំងឺផ្លូវចិត្ត បញ្ហាផ្លូវភេទ និងសខុភាពបន្តរពូជប្រចាំអាសុី',
    latitude: null,
    longitude: null,
    facility_batch_id: 1,
    image_url: '',
    audio_url: '',
    audio: '',
    image: require('../../assets/images/intro_2.jpg'),
  }
];