export const ERROR_AUTHENTICATION = 'ERROR_AUTHENTICATION';
export const ERROR_UNAUTHORIZED = 'ERROR_UNAUTHORIZED';
export const ERROR_NOT_FOUND = 'ERROR_NOT_FOUND';
export const ERROR_UNPROCESSABLE = 'ERROR_UNPROCESSABLE';
export const ERROR_NETWORK_AUTHENTICATION = 'ERROR_NETWORK_AUTHENTICATION';
export const ERROR_SOMETHING_WENT_WRONG = 'ERROR_SOMETHING_WENT_WRONG';