const imageSources = {
  intro1: require('../assets/images/intro1.png'),
  intro2: require('../assets/images/intro2.png'),
  intro3: require('../assets/images/intro3.png'),
  intro4: require('../assets/images/intro4.png'),
  noBackgroundImg: require('../assets/images/img_no_background.png'),
  'birth_control.png': require("../assets/images/categories/birth_control.png"),
  'clinic_and_examination_service.png': require("../assets/images/categories/clinic_and_examination_service.png"),
  'consensus_and_forced.png': require("../assets/images/categories/consensus_and_forced.png"),
  'counseling_and_emotional_support.png': require("../assets/images/categories/counseling_and_emotional_support.png"),
  'entertainment.png': require("../assets/images/categories/entertainment.png"),
  'hiv_virus.png': require("../assets/images/categories/hiv_virus.png"),
  'menstruation.png': require("../assets/images/categories/menstruation.png"),
  'mental_support.png': require("../assets/images/categories/mental_support.png"),
  'adult_physical_change.png': require("../assets/images/categories/adult_physical_change.png"),
  'protection_from_sexual_abuse.png': require("../assets/images/categories/protection_from_sexual_abuse.png"),
  'reproduction.png': require("../assets/images/categories/reproduction.png"),
  'reproduction_health.png': require("../assets/images/categories/reproduction_health.png"),
  'reproductive_right.png': require("../assets/images/categories/reproductive_right.png"),
  'sex_differences.png': require("../assets/images/categories/sex_differences.png"),
  'sexual_desire.png': require("../assets/images/categories/sexual_desire.png"),
  'sexual_education.png': require("../assets/images/categories/sexual_education.png"),
  'sexual_health_social_and_gender.png': require("../assets/images/categories/sexual_health_social_and_gender.png"),
  'sexual_orientation.png': require("../assets/images/categories/sexual_orientation.png"),
  'sti_virus.png': require("../assets/images/categories/sti_virus.png"),
  'understanding_gender.png': require("../assets/images/categories/understanding_gender.png"),
  'violence_and_emotional_control.png': require("../assets/images/categories/violence_and_emotional_control.png"),
  'hiv_virus.png': require("../assets/images/categories/hiv_virus.png"),
  'drug_and_alcohol_prevention.png': require("../assets/images/categories/drug_and_alcohol_prevention.png"),
  'understanding_hiv.png': require("../assets/images/categories/understanding_hiv.png"),
  'hiv_aids_awareness.png': require("../assets/images/categories/hiv_aids_awareness.png"),
  'hiv_testing.png': require("../assets/images/categories/hiv_testing.png"),
  'hiv_aids_treatment.png': require("../assets/images/categories/hiv_aids_treatment.png"),
  'understanding_prevention_and_control_laws.png': require("../assets/images/categories/understanding_prevention_and_control_laws.png"),
  'youth_migration.png': require("../assets/images/categories/youth_migration.png"),
  rhac: require("../assets/images/rhac_logo.png"),
  marie_stopes: require("../assets/images/marie_stopes_logo.png"),
  chhouk_sar: require("../assets/images/chhouk_sar_logo.jpeg")
}

export default imageSources;