const imageSources = {
  intro1: require('../assets/images/intro1.png'),
  intro2: require('../assets/images/intro2.png'),
  intro3: require('../assets/images/intro3.png'),
  intro4: require('../assets/images/intro4.png'),
  noBackgroundImg: require('../assets/images/img_no_background.png'),
  birth_control: require("../assets/images/categories/birth_control.png"),
  clinic_service: require("../assets/images/categories/clinic_and_examination_service.png"),
  consensus_forced: require("../assets/images/categories/consensus_and_forced.png"),
  counseling_emotional_support: require("../assets/images/categories/counseling_and_emotional_support.png"),
  entertainment: require("../assets/images/categories/entertainment.png"),
  hiv_virus: require("../assets/images/categories/hiv_virus.png"),
  menstruation: require("../assets/images/categories/menstruation.png"),
  mental_support: require("../assets/images/categories/mental_support.png"),
  physical_change: require("../assets/images/categories/adult_physical_change.png"),
  protection_abuse: require("../assets/images/categories/protection_from_sexual_abuse.png"),
  reproduction: require("../assets/images/categories/reproduction.png"),
  reproduction_health: require("../assets/images/categories/reproduction_health.png"),
  reproductive_right: require("../assets/images/categories/reproductive_right.png"),
  sex_differences: require("../assets/images/categories/sex_differences.png"),
  sexual_desire: require("../assets/images/categories/sexual_desire.png"),
  sexual_education: require("../assets/images/categories/sexual_education.png"),
  sexual_health: require("../assets/images/categories/sexual_health_social_and_gender.png"),
  sti_virus: require("../assets/images/categories/sti_virus.png"),
  understanding_gender: require("../assets/images/categories/understanding_gender.png"),
  violence_emotional_control: require("../assets/images/categories/violence_and_emotional_control.png"),
}

export default imageSources;