export const schemaNames = [
  'User',
  'Category',
  'Visit',
  'Facility',
  'Video',
  'Topic',
  'Question',
  'Option',
  'SearchHistory',
  'Notification',
  'Tag',
  'FacilityImage',
  'VideoAuthor',
  'DownloadedFile',
];